# Generated by Django 3.2.18 on 2023-09-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_tp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buys',
            fields=[
                ('transition_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('purchased', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('status_id', models.BooleanField(default=True)),
                ('leftovers', models.IntegerField(default=0)),
                ('skin', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Gw2tpBuys',
        ),
    ]
