# Generated by Django 3.2.18 on 2023-09-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_tp', '0002_auto_20230906_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='buys',
            name='selling_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
