# Generated by Django 3.2.18 on 2023-09-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_tp', '0003_auto_20230907_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='status_id',
            new_name='sales_flag',
        ),
        migrations.AddField(
            model_name='items',
            name='maximum_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='price_now',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
