# Generated by Django 3.2.18 on 2023-09-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_tp', '0004_auto_20230907_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='sales_flag',
        ),
        migrations.AddField(
            model_name='items',
            name='status_id',
            field=models.BooleanField(default=True),
        ),
    ]
