# Generated by Django 3.2.18 on 2023-09-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_tp', '0007_alter_items_sales_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSells',
            fields=[
                ('transition_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('created', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('transition_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('purchased', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
