# Generated by Django 3.2.18 on 2023-09-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_tp', '0008_currentsells_sells'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buys',
            name='purchased',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sells',
            name='purchased',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
