# Generated by Django 3.2.18 on 2023-09-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_tp', '0009_auto_20230908_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('selling_price', models.IntegerField(blank=True, null=True)),
                ('price_now', models.IntegerField(blank=True, null=True)),
                ('maximum_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='buys',
            name='selling_price',
        ),
    ]
