# Generated by Django 3.2.18 on 2023-09-11 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_tp', '0010_auto_20230911_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='item_id',
        ),
        migrations.AddField(
            model_name='price',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gw2_tp.items'),
        ),
    ]
