# Generated by Django 3.2.18 on 2023-09-11 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_tp', '0011_auto_20230911_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='leftovers',
        ),
        migrations.RemoveField(
            model_name='items',
            name='maximum_price',
        ),
        migrations.RemoveField(
            model_name='items',
            name='price_now',
        ),
        migrations.RemoveField(
            model_name='items',
            name='sales_flag',
        ),
        migrations.CreateModel(
            name='Leftovers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currently_available', models.IntegerField(blank=True, null=True)),
                ('item_num', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gw2_tp.items')),
            ],
        ),
    ]
