# Generated by Django 3.2.18 on 2023-09-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_tp', '0013_auto_20230912_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leftovers',
            name='item_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='price',
            name='item_id',
            field=models.IntegerField(),
        ),
    ]
