# Generated by Django 3.2.18 on 2023-09-12 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_tp', '0014_auto_20230912_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leftovers',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='price',
            name='item_id',
        ),
        migrations.AddField(
            model_name='leftovers',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gw2_tp.items'),
        ),
        migrations.AddField(
            model_name='price',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gw2_tp.items'),
        ),
    ]
