# Generated by Django 3.2.18 on 2023-09-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_tp', '0015_auto_20230912_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='skin',
            field=models.BooleanField(default=False),
        ),
    ]
