# Generated by Django 3.2.18 on 2023-09-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw2_tp', '0016_alter_items_skin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='skin',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
