name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          # Your build and test commands here
          # For example:
          # npm install
          # npm test


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Production
      uses: actions/checkout@v3

    - name: Deploy to Hosting
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PATH: ${{ secrets.SSH_PATH }}
        SSH_END_POINT: ${{ secrets.SSH_END_POINT }}

      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan $SSH_END_POINT >> ~/.ssh/known_hosts
        ssh -i ~/.ssh/id_rsa "$SSH_USER" "cd $SSH_PATH/public_html/ae563_site/ && git checkout db.sqlite3 && git pull"
