name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Hosting
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_PATH: ${{ secrets.SSH_PATH }}
        SSH_END_POINT: ${{ secrets.SSH_END_POINT }}

      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan $SSH_END_POINT >> ~/.ssh/known_hosts
        ssh -i ~/.ssh/id_rsa "$SSH_USER" "cd $SSH_PATH/public_html/test_deploy2/"
